name: schedule trigger

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          rm -f e.xml && wget https://epg.112114.xyz/pp.xml -O e.xml


          
