name: schedule trigger

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          rm -f e.xml && wget http://47.101.186.10/jlp?m=223 -O e.xml
          git config user.name "diandzhang" 
          git config user.email "diandzhang@gmail.com"
          git add e.xml
          git commit --quiet -m "test"
          git push -f origin main


          
